org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.16.5
fabric_loader_version=0.19.3
fabric_api_version=0.42.0+1.16
loader_version_range=>=0.14.0

mod_id=dglabcraft
mod_name=DGLab Craft
mod_license=GPL-3.0
mod_version=1.1.2
mod_group_id=com.lumoren.dglabcraft
mod_authors=Lumoren
mod_description=Sends physical feedback to DGLab device based on in-game events

systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=7890
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=7890
