# This is an example mods.toml file for NeoForge.
modLoader="javafml"
loaderVersion="[4,)"
license="${mod_license}"

[[mods]]
modId="dglabcraft"
version="1.0.0"
displayName="DGLab Craft"
authors="Lumoren"

description="DGLab physical feedback mod for Minecraft 1.21.1"

[[dependencies.dglabcraft]]
modId="neoforge"
mandatory=true
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.dglabcraft]]
modId="minecraft"
mandatory=true
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"
